#!/usr/bin/env bash
#gives information about the school file
file="school"
if [ -e "$file" ]; then
	echo "school file exists"
	if [ ! -s "$file" ]; then
		echo "school file is empty"
	elif [ -s "$file" ]; then 
		echo "school file is not empty"
	elif [ -f "$file" ]; then
		echo "school is a regular file" 
	fi	
else 
	echo "school file does not exist"
fi	

